version: 1
builder:
  configs:
    - documentation_targets: [FCPKit, FCPKitMediaTools, FCPXMLDiff, FCPKitDSL]
      swift_version: "6.4"
      custom_documentation_parameters: [--include-extended-types]
