//
//  SchemaCompletenessReportRenderer.swift
//  FCPKit
//
//  Created by Leo Dion.
//  Copyright © 2026 BrightDigit.
//
//  Permission is hereby granted, free of charge, to any person
//  obtaining a copy of this software and associated documentation
//  files (the "Software"), to deal in the Software without
//  restriction, including without limitation the rights to use,
//  copy, modify, merge, publish, distribute, sublicense, and/or
//  sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following
//  conditions:
//
//  The above copyright notice and this permission notice shall be
//  included in all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
//  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
//  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
//  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//  OTHER DEALINGS IN THE SOFTWARE.
//

import FCPKit
import Foundation

/// Renders a schema-completeness report as JSON or Markdown.
public struct SchemaCompletenessReportRenderer: Sendable {
  /// Creates a renderer.
  public init() {}

  /// Encodes a schema-completeness report as pretty-printed JSON data.
  public func jsonData(_ report: SchemaCompletenessReport) throws -> Data {
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
    return try encoder.encode(report)
  }

  /// Renders a schema-completeness report as Markdown.
  public func markdown(_ report: SchemaCompletenessReport) -> String {
    var lines = [
      "# FCPKit Schema Completeness Report",
      "",
      "Generated by `fcpxml-diff schema-completeness` from decode/re-encode structural loss.",
      "",
      "## Summary",
      "",
      "| Files | Dropped elements | Dropped attributes | Dropped text | Total |",
      "| ---: | ---: | ---: | ---: | ---: |",
      summaryRow(report),
      "",
      "## Normalization",
      "",
    ]
    lines.append(contentsOf: report.normalization.map { "- \($0)" })
    lines += ["", "## Aggregate Findings", ""]
    appendFindings(report.aggregateFindings, to: &lines)

    for file in report.files {
      lines += [
        "",
        "## \(file.path)",
        "",
        "FCPXML version: `\(file.fcpxmlVersion ?? "unknown")`",
        "",
        lossSentence(file.summary),
        "",
      ]
      appendFindings(file.findings, to: &lines)
    }
    return lines.joined(separator: "\n") + "\n"
  }

  private func summaryRow(_ report: SchemaCompletenessReport) -> String {
    let totals = report.totals
    let counts = [
      report.files.count,
      totals.droppedElements,
      totals.droppedAttributes,
      totals.droppedText,
      totals.total,
    ]
    return "| " + counts.map(String.init).joined(separator: " | ") + " |"
  }

  private func lossSentence(_ summary: SchemaCompletenessSummary) -> String {
    "Dropped elements: \(summary.droppedElements); "
      + "dropped attributes: \(summary.droppedAttributes); "
      + "dropped text: \(summary.droppedText)."
  }

  private func appendFindings(
    _ findings: [FCPXMLDifference],
    to lines: inout [String]
  ) {
    if findings.isEmpty {
      lines.append("No structural loss detected.")
      return
    }
    lines += [
      "| Count | Kind | Structural path |",
      "| ---: | --- | --- |",
    ]
    lines.append(
      contentsOf: findings.map {
        "| \($0.count) | `\($0.kind.rawValue)` | `\($0.path)` |"
      }
    )
  }
}
